# Generated by Django 6.0.3 on 2026-03-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='father_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familymember',
            name='mother_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familymember',
            name='middle_name',
            field=models.CharField(max_length=100),
        ),
    ]
