# Generated by Django 6.0.3 on 2026-04-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_familymember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='familymember',
            name='instagram',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='familymember',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
