# Generated by Django 6.0.3 on 2026-04-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_familymember_facebook_familymember_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
