# Generated by Django 6.0.3 on 2026-03-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_familymember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=10),
        ),
    ]
