# Generated by Django 6.0.3 on 2026-03-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_familymember_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
